name: 🚀 Deploy til One.com (FTPS - sikkerjob.dk)

on:
  push:
    branches:
      - main

jobs:
  ftps-deploy:
    name: Upload til One.com via FTPS
    runs-on: ubuntu-latest

    steps:
      - name: Hent seneste kode
        uses: actions/checkout@v4

      - name: Upload filer til One.com via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /public_html/
          local-dir: ./
