name: 🚀 Deploy til One.com (SFTP - sikkerjob.dk)

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: Upload til One.com via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Hent seneste kode
        uses: actions/checkout@v4

      - name: Upload filer til One.com via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          server-dir: /public_html/
          local-dir: ./
          git-ftp-args: --insecure
